title: AIWiSe Exploration Tool docs
lang: en
description: Welcome to the AIWiSE Exploration Tool documentation!


remote_theme: rundocs/jekyll-rtd-theme

readme_index:
  with_frontmatter: true

exclude:
  - Makefile
  - CNAME
  - Gemfile
  - Gemfile.lock
